package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.27

import (
	"context"
	"go-web/ent"
	"go-web/ent/user"
)

// UpdatePasswordByAccount is the resolver for the updatePasswordByAccount field.
func (r *mutationResolver) UpdatePasswordByAccount(ctx context.Context, account string, password string) (bool, error) {
	_, err := r.client.User.Query().Where(user.Account(account)).First(ctx)
	if err != nil {
		return false, err
	}

	if err := r.client.User.Update().Where(user.Account(account)).SetPassword(password).Exec(ctx); err != nil {
		return false, err
	}
	return true, nil
}

// UserByAccount is the resolver for the userByAccount field.
func (r *queryResolver) UserByAccount(ctx context.Context, account string) (*ent.User, error) {
	return r.client.User.Query().Where(user.Account(account)).First(ctx)
}
