// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"go-web"
	"go-web/interface/http"
	"go-web/interface/resolvers"
	"go-web/interface/router"
	"go-web/pkg/log"
	"go-web/pkg/mysql"
	"go-web/pkg/redis"
)

// Injectors from wire.go:

func Create() (*go_web.Server, error) {
	context := go_web.NewTopLevelCtx()
	logger := log.NewLogger()
	client := mysql.NewMysql(logger)
	service := redis.NewRedis(context)
	config := resolvers.NewConfig(client, service)
	server := resolvers.NewGraphqlHandler(config, client)
	initRoutersFunc := router.CreateInitRoutesFunc(server)
	engine := http.NewRouter(logger, initRoutersFunc)
	httpServer := http.NewServer(logger, engine)
	go_webServer := go_web.NewServer(context, httpServer, logger)
	return go_webServer, nil
}

// wire.go:

var providerSet = wire.NewSet(log.ProviderSet, go_web.ProviderSet, http.ProviderSet, mysql.ProviderSet, redis.ProviderSet, router.ProviderSet)
