// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-web"
	"go-web/interface/http"
	"go-web/interface/resolvers"
	"go-web/interface/router"
	"go-web/pkg/cache"
	"go-web/pkg/config"
	"go-web/pkg/log"
	"go-web/pkg/mysql"
	"go-web/pkg/redis"
)

// Injectors from wire.go:

func Create(cfg *config.Config) (*go_web.Server, error) {
	context := go_web.NewTopLevelCtx()
	logger := log.NewLogger()
	redisClient, err := cache.NewRedisClient(cfg, logger)
	if err != nil {
		return nil, err
	}
	client := mysql.NewMysql(cfg, logger)
	service := redis.NewRedis(context)
	graphConfig := resolvers.NewConfig(client, service, logger)
	client2 := redis.ProvideGoRedisClient(service)
	server := resolvers.NewGraphqlHandler(graphConfig, client, client2, logger)
	initRoutersFunc := router.CreateInitRoutesFunc(server)
	engine := http.NewRouter(logger, redisClient, initRoutersFunc)
	httpServer := http.NewServer(logger, engine)
	go_webServer := go_web.NewServer(context, httpServer, logger, cfg)
	return go_webServer, nil
}
